### ISSUE TITLE
RoR group project: set up Kanban board

### ISSUE THREAD

**Issue by Kaiserabbas** [Kaiserabbas/food_recipe#13]
# Kanban Board Setup
https://github.com/users/Kaiserabbas/projects/3/views/1

Hi, We are total of two people working on this project:
- @Kaiserabbas 
- @coker2019 

- Created tasks on Kanban board based on the project requirements.
- Each task is a separate card that:
- Has a descriptive title.
- Has the number of points in the [Xpt] prefix.

**Comment by LionRouge1** [comment]
Hi @Kaiserabbas, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no information about how many people are in your group.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by LionRouge1** [comment]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

## Highlights
- Great job, assigning each card to a team member :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- Each requirement has at least one corresponding card in the Kanban board  :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
